import sys
import pygame

class UI:
    def __init__(self):
        pygame.init()
        self.width = 700
        self.height = 630
        self.screen = pygame.display.set_mode((self.width, self.height))
        self.cell_size = 70
        pygame.display.set_caption("Ohte-chess")

    def draw(self, board):
        self.screen.fill((100,100,100))
        while True:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.MOUSEBUTTONDOWN:
                    if event.button == 1:
                        mouseX, mouseY = event.pos
                        print(f"Left Mouse Click at ({mouseX}, {mouseY})")

            for i in range(8):
                for j in range(1,9):
                    x = j * self.cell_size
                    y = i * self.cell_size

                    if (i + j) % 2 == 0:
                        color = (255, 255, 255)
                    else:
                        color = (0, 0, 0)

                    pygame.draw.rect(self.screen, color, (x, y, self.cell_size, self.cell_size))
            #draw letters, generated by chatgpt, edited heavily
            for i in range(0,9):
                row = [" ", "A", "B", "C", "D", "E", "F", "G", "H"]
                font = pygame.font.Font(None, 55)
                text = font.render(row[i], True, (0, 0, 0))

                text_rect = text.get_rect(center=(i * self.cell_size + self.cell_size // 2, 8.5 * self.cell_size))
                self.screen.blit(text, text_rect)
            #generated code ends
            
            for i in range(0,9):
                row = ["1", "2", "3", "4", "5", "6", "7", "8", " "]
                font = pygame.font.Font(None, 55)
                text = font.render(row[i], True, (0, 0, 0))

                text_rect = text.get_rect(center=(self.cell_size // 2, i * self.cell_size + self.cell_size // 2))
                self.screen.blit(text, text_rect)
            pygame.display.flip()